//
//  RegisterPresenter.swift
//  Tests
//
//  Created Kelly Jocelyn Farías Gómez on 31/01/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class RegisterPresenter {
    weak private var view: RegisterViewProtocol?
    var interactor: RegisterInteractorInputProtocol?
    private let router: RegisterWireframeProtocol

    init(interface: RegisterViewProtocol, interactor: RegisterInteractorInputProtocol?, router: RegisterWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

extension RegisterPresenter: RegisterPresenterProtocol {
    
}

extension RegisterPresenter: RegisterInteractorOutputProtocol {
    
}
