//
//  RegisterViewController.swift
//  Tests
//
//  Created Kelly Jocelyn Farías Gómez on 31/01/24.
//  Template generated by UPAX Zeus
//

import UIKit

class RegisterViewController: BasicViewController {
	var presenter: RegisterPresenterProtocol?
    
    /// Views for this controller
    let mainView = RegisterView()

	override func viewDidLoad() {
        super.viewDidLoad()
        mainView.viewContainer=contentView
        mainView.addViews()
        setupGestures()
    }
    
    private func setupGestures() {
        
    }
}

extension RegisterViewController: RegisterViewProtocol {
    
}
