//
//  RegisterView.swift
//  Tests
//
//  Created Kelly Jocelyn Farías Gómez on 31/01/24.
//  Template generated by UPAX Zeus
//

import UIKit

class RegisterView: UIView {
    // MARK: Child views
    
   /* let scrollContent:UIScrollView={
        let scroll=UIScrollView()
        scroll.translatesAutoresizingMaskIntoConstraints = false
        return scroll
    }()
    
   let viewContainer:UIView={
        let view=UIView()
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()*/
    var viewContainer:UIView?{
        didSet{
            addViews()
            setupConstraints()
        }
    }
    let stackV:UIStackView={
        let stack=UIStackView()
        stack.translatesAutoresizingMaskIntoConstraints = false
        stack.axis = .vertical
        stack.spacing = 10
        stack.setup(cornerRadious: 10)
        
        return stack
    }()
    
    
    // MARK: Initializers
    init() {
        super.init(frame: .zero)
    }
   
    
    required init?(coder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
}
