//
//  RegisterInteractor.swift
//  Tests
//
//  Created Kelly Jocelyn Farías Gómez on 31/01/24.
//  Copyright © 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by UPAX Zeus
//

import UIKit

class RegisterInteractor: RegisterInteractorInputProtocol {
    weak var presenter: RegisterInteractorOutputProtocol?
}
