//
//  RegisterView+Layout.swift
//  Tests
//
//  Created Kelly Jocelyn Farías Gómez on 31/01/24.
//  Template generated by UPAX Zeus
//

import UIKit

extension RegisterView {
    func addViews() {
        viewContainer?.addSubview(stackV)
        
        for _ in 0...5{
            let lbl=UILabel()
            lbl.translatesAutoresizingMaskIntoConstraints = false
            lbl.text = "Hola"
            NSLayoutConstraint.activate([
                lbl.heightAnchor.constraint(greaterThanOrEqualToConstant: 50)
            ])
            stackV.addArrangedSubview(lbl)
        }
    }
    
    func setupConstraints() {
        guard let viewContainer=self.viewContainer else{return}
        NSLayoutConstraint.activate([
            //ViewContant
            stackV.topAnchor.constraint(equalTo: viewContainer.topAnchor,constant: 10),
            stackV.bottomAnchor.constraint(equalTo: viewContainer.bottomAnchor,constant: -10),
            stackV.leadingAnchor.constraint(equalTo: viewContainer.leadingAnchor,constant: 10),
            stackV.trailingAnchor.constraint(equalTo: viewContainer.trailingAnchor,constant: -10),
            
        ])
    }
}
